### ISSUE TITLE
Invalid metadata.yaml and invalid http address

### ISSUE THREAD

**Issue by philpott** [rtbhouse-apps/gtm-tag-template-hosted-js#1]
https://github.com/rtbhouse-apps/gtm-tag-template-hosted-js/blob/3a39481a8582215b21f1723980a97fb91bc917be/metadata.yaml#L1-L2

To fix the metadata.yaml file you need to remove the trailing commas in rtbhouse.com

```
YAMLError: end of the stream or a document separator is expected at line 1, column 37:
  homepage: "https://www.rtbhouse,com",
                                      ^ at line 1, column 37:
  homepage: "https://www.rtbhouse,com",
```

Looking at the URL it also has a comma instead of a pirod between rtbhouse.com

**Comment by pawelmisiewicz-rtbh** [comment]
@philpott 
Issue has been fixed in https://github.com/rtbhouse-apps/gtm-tag-template-hosted-js/commit/e33c9610d83a03d2b9f4d6294fe2c7e47ab2292e
