### ISSUE TITLE
Tags fired marked as "Still running"

### ISSUE THREAD

**Issue by rafa-suagu** [rtbhouse-apps/gtm-tag-template-hosted-js#4]
Implementing the tracking with this GTM Custom Template we get the "Still running" state on each event that we send except with the Base Tag.

The reason is simple, except the Base Tag, the required callback `data.gtmOnSuccess()` / `data.gtmOnFailure()` is not called.

Just adding the callback on the other events, this issue would be done.

FYI: https://www.simoahava.com/analytics/still-running-google-tag-manager-tags/

**Comment by dgrzywacz-rtbh** [comment]
thanks for reporting @rafa-as, we'll look into this and let you know

**Comment by rafa-suagu** [comment]
@abahdanovich @dgrtbh thanks for merging the PR! Do you know when can you make a release to GTM Templates to update our template?

**Comment by dgrzywacz-rtbh** [comment]
@rafa-as we need an additional review before this goes live, we'll keep you posted. Sorry for the wait!

**Comment by rafa-suagu** [comment]
Thanks for the update @dgrtbh !

**Comment by dgrzywacz-rtbh** [comment]
@rafa-as I got information that this change was deployed, so I'm closing this for now, but let me know if you have any comments regarding this, and thanks again for reporting 🙂

**Comment by rafa-suagu** [comment]
Thank you @dgrtbh! We've already update our GTM template and everything works properly! A pleasure!
